In [75]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

df = pd.read_csv(r"C:\Users\adishree.b\Documents\practice datasets\WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [4]:
df.head(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

In [5]:
df.describe(include = 'object')

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,6615-ZGEDR,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No
freq,1,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

In [6]:
col_names = df.select_dtypes(include='object').columns
for i in col_names:
    print(i, '\n' ,df[i].value_counts(), '\n')

customerID
 6615-ZGEDR    1
8327-WKMIE    1
8433-WPJTV    1
4565-EVZMJ    1
2065-MMKGR    1
             ..
6905-NIQIN    1
0722-SVSFK    1
6087-MVHJH    1
7394-FKDNK    1
0916-QOFDP    1
Name: customerID, Length: 7043, dtype: int64

gender
 Male      3555
Female    3488
Name: gender, dtype: int64

Partner
 No     3641
Yes    3402
Name: Partner, dtype: int64

Dependents
 No     4933
Yes    2110
Name: Dependents, dtype: int64

PhoneService
 Yes    6361
No      682
Name: PhoneService, dtype: int64

MultipleLines
 No                  3390
Yes                 2971
No phone service     682
Name: MultipleLines, dtype: int64

InternetService
 Fiber optic    3096
DSL            2421
No             1526
Name: InternetService, dtype: int64

OnlineSecurity
 No                     3498
Yes                    2019
No internet service    1526
Name: OnlineSecurity, dtype: int64

OnlineBackup
 No                     3088
Yes                    2429
No internet service    1526
Name: OnlineBackup, dtype: int64

DeviceProtection
 No                     3095
Yes                    2422
No internet service    1526
Name: DeviceProtection, dtype: int64

TechSupport
 No                     3473
Yes                    2044
No internet service    1526
Name: TechSupport, dtype: int64

StreamingTV
 No                     2810
Yes                    2707
No internet service    1526
Name: StreamingTV, dtype: int64

StreamingMovies
 No                     2785
Yes                    2732
No internet service    1526
Name: StreamingMovies, dtype: int64

Contract
 Month-to-month    3875
Two year          1695
One year          1473
Name: Contract, dtype: int64

PaperlessBilling
 Yes    4171
No     2872
Name: PaperlessBilling, dtype: int64

PaymentMethod
 Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: PaymentMethod, dtype: int64

TotalCharges
 20.2       11
           11
19.75       9
20.05       8
19.9        8
           ..
2193.65     1
3399.85     1
263.05      1
830.85      1
25.35       1
Name: TotalCharges, Length: 6531, dtype: int64

Churn
 No     5174
Yes    1869
Name: Churn, dtype: int64

In [20]:
gendertypes = df[['gender','PhoneService']].columns
for i in gendertypes:
    print(i +'\n',df[i].value_counts(), '\n')

gender
 Male      3555
Female    3488
Name: gender, dtype: int64

PhoneService
 Yes    6361
No      682
Name: PhoneService, dtype: int64

In [62]:
df.select_dtypes(include='object').columns

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges',
       'Churn'],
      dtype='object')

In [101]:
variables = df[['gender', 'Partner', 'Dependents',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod']]
df_dum = pd.get_dummies(variables, drop_first=False)

In [102]:
df_dum = df_dum.astype(float)

In [103]:
df_dum.head(2)

,gender_Female,gender_Male,Partner_No,Partner_Yes,Dependents_No,Dependents_Yes,MultipleLines_No,MultipleLines_No phone service,MultipleLines_Yes,InternetService_DSL,...,StreamingMovies_Yes,Contract_Month-to-month,Contract_One year,Contract_Two year,PaperlessBilling_No,PaperlessBilling_Yes,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [104]:
df_dum[['customerID','Churn']]=df[['customerID','Churn']]
df_dum['Churn']=np.where(df['Churn']=='Yes',1,0)
df_dum['Churn']=df_dum['Churn'].astype(float)
targets = df_dum[['Churn']]
predictors = df_dum.drop(['Churn','customerID'], axis=1)

In [105]:
#df_dum['customerID']=df['customerID']
#targets = df_dum[['Churn_No','Churn_Yes']]
#predictors = df_dum.drop(['Churn_No','Churn_Yes','customerID'], axis=1)

In [121]:
X_train, X_test, y_train, y_test = train_test_split(predictors, targets, test_size=0.2)

# Now, let's split the train data into train and validation dataset in (75:25): which will result in the 60% and 20 % of whole dataset

#X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25)

In [122]:
generated_inputs = predictors

generated_targets = targets

# save into an npz file called "TF_intro"
np.savez('TF_intro', inputs=generated_inputs, targets=generated_targets)

# Load the training data from the NPZ
training_data = np.load('TF_intro.npz')

In [123]:
predictors.shape

(7043, 39)

In [124]:
input_size = 39
output_size = 1
# Use same hidden layer size for both hidden layers. Not a necessity.
hidden_layer_size = 10
    
# define how the model will look like
model = tf.keras.Sequential([
    
    # tf.keras.layers.Dense is basically implementing: output = activation(dot(input, weight) + bias)
    # it takes several arguments, but the most important ones for us are the hidden_layer_size and the activation function
    tf.keras.layers.Dense(hidden_layer_size, activation='relu'), # 1st hidden layer
    tf.keras.layers.Dense(hidden_layer_size, activation='relu'), # 2nd hidden layer
    tf.keras.layers.Dense(hidden_layer_size, activation='relu'), # 2nd hidden layer
    
    # the final layer is no different, we just make sure to activate it with softmax
    tf.keras.layers.Dense(output_size, activation='softmax') # output layer
])

In [125]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [127]:
NUM_EPOCHS = 10

# we fit the model, specifying the
# training data
# the total number of epochs
# and the validation data we just created ourselves in the format: (inputs,targets)
model.fit(training_data['inputs'], training_data['targets'],epochs=NUM_EPOCHS, verbose =2)

Epoch 1/10

InvalidArgumentError: Received a label value of 1 which is outside the valid range of [0, 1).  Label values: 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0
	 [[{{node loss/output_1_loss/sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_keras_scratch_graph_898]